### ISSUE TITLE
版本能否支持8.0,我想用pod啊

### ISSUE THREAD

**Issue by LceAwn** [xiangwangfeng/M80TableViewComponent#2]
版本能否支持8.0,我想用pod啊

**Comment by xiangwangfeng** [comment]
理论上是支持 8.0 的，但是原来工程中都是从 9.0 开始支持。并没有特殊限制无法在 8.0 使用

**Comment by LceAwn** [comment]
<img width="568" alt="屏幕快照 2019-09-09 上午9 26 47" src="https://user-images.githubusercontent.com/16110254/64497863-05037580-d2e4-11e9-8252-1f827a076fbb.png">
是pod上的版本最低目前是target,我的项目是8.0,所以只能手动导入,不能使用pod导入

**Comment by LceAwn** [comment]
是pod上的版本最低目前是target9.0,我的项目是8.0,所以只能手动导入,不能使用pod导入
